services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: charm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: charm
      POSTGRES_USER: charm
      POSTGRES_PASSWORD: charm
      TZ: Asia/Tokyo
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U charm"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 1s
