packages:
  - packages/**/*
  - apps/**/*

catalog:
  '@biomejs/biome': 2.3.13
  '@cloudflare/vite-plugin': ^1.2.3
  hono: ^4.11.10
  npm-run-all2: 8.0.4
  qr-code-styling: ^1.9.2
  vite: ^6.3.5
  vite-ssr-components: ^0.5.2
  vitest: ^4.0.18
  workerd: 1.20260214.0
  wrangler: ^4.17.0

catalogMode: strict

cleanupUnusedCatalogs: true

dedupeInjectedDeps: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

injectWorkspacePackages: true

linkWorkspacePackages: true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - hono

preferWorkspacePackages: true

saveWorkspaceProtocol: false

sharedWorkspaceLockfile: true
